import { existsSync, writeFileSync, unlinkSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const DEV_ENV_FILE = resolve(ROOT, '.env.development.local')

export function writeDevelopmentEnv(runtime) {
  writeFileSync(
    DEV_ENV_FILE,
    [
      '# Auto-generated by npm run dev:local – nepřepisujte ručně',
      `# API URL (pro mobil použijte LAN IP z výstupu terminálu)`,
      `VITE_SUPABASE_URL=${runtime.url}`,
      `VITE_SUPABASE_ANON_KEY=${runtime.anonKey}`,
      `VITE_INITIAL_ADMIN_EMAIL=${runtime.adminEmail ?? 'admin@vhbulldig.cz'}`,
      '',
    ].join('\n')
  )
}

export function removeDevelopmentEnv() {
  if (existsSync(DEV_ENV_FILE)) unlinkSync(DEV_ENV_FILE)
}
