-- PDF 8 KRITICKÁ OPRAVA – výchozí červená barva markeru (produkční SQL Editor)
--
-- Spusťte v tomto pořadí (nebo jen 078 pokud už máte 076–077):
--   1. supabase/migrations/076_pdf8_marker_color_no_diary.sql
--   2. supabase/migrations/077_pdf8_marker_color_approved_only.sql
--   3. supabase/migrations/078_pdf8_critical_default_red_marker.sql
